In [1]:
type("Hello, World!")

str

In [2]:
type(17)

int

In [1]:
type(3.2)

float

In [2]:
type("17")

str

In [3]:
type("3.2")

str

In [4]:
type('This is a string.')

str

In [5]:
type("And so is this.")

str

In [6]:
type("""and this.""")

str

In [7]:
type('''and even this...''')

str

In [8]:
print('''"Oh no", she exclaimed, "Ben's bike is broken!"''')

"Oh no", she exclaimed, "Ben's bike is broken!"


In [9]:
message = """This message will

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-9-b86ec3dfc327>, line 1)

In [12]:
message = """This message will
... span several
... lines."""
print(message)

This message will
span several
lines.


In [13]:
'This is a string.'

'This is a string.'

In [14]:
"""And so is this."""

'And so is this.'

In [15]:
42000

42000

In [16]:
42,000

(42, 0)

In [17]:
message = "What's up, Doc?"
n = 17
pi = 3.14159

In [18]:
17 = n

SyntaxError: can't assign to literal (<ipython-input-18-beb598da8e38>, line 1)

In [20]:
message
'What's up, Doc?'
n

SyntaxError: invalid syntax (<ipython-input-20-6f6945912440>, line 2)

In [22]:
message

"What's up, Doc?"

In [23]:
n

17

In [24]:
pi

3.14159

In [25]:
day = "Thursday"
day

'Thursday'

In [26]:
day = "Friday"
day

'Friday'

In [27]:
day = 21
day

21

In [28]:
76trombones = "big parade"

SyntaxError: invalid syntax (<ipython-input-28-71e3d5cede32>, line 1)

In [29]:
more$ = 1000000

FileNotFoundError: [Errno 2] No such file or directory: '$ = 1000000'

In [30]:
class = "Computer Science 101"

SyntaxError: invalid syntax (<ipython-input-30-d7ae8131708c>, line 1)

In [31]:
1 + 1

2

In [32]:
len("hello")

5

In [33]:
17

17

In [35]:
y = 3.14
x = len("hello")
x

5

In [36]:
y

3.14

In [37]:
2 ** 3

8

In [38]:
3 ** 2

9

In [39]:
minutes = 645
hours = minutes / 60
hours

10.75

In [40]:
7 / 4

1.75

In [41]:
7 // 4

1

In [42]:
minutes = 645
hours = minutes // 60
hours

10

In [43]:
int(3.14)

3

In [44]:
int(3.9999)

3

In [45]:
int(3.0)

3

In [46]:
int(-3.999)

-3

In [47]:
int(minutes / 60)

10

In [48]:
int("2345")

2345

In [49]:
int(17)

17

In [50]:
int("23 bottles")

ValueError: invalid literal for int() with base 10: '23 bottles'

In [51]:
float(17)

17.0

In [52]:
float("123.45")

123.45

In [53]:
str(17)

'17'

In [54]:
str(123.45)

'123.45'

In [55]:
2 ** 3 ** 2

512

In [56]:
(2 ** 3) ** 2

64

In [57]:
message - 1

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [58]:
"Hello" / 123

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [59]:
message * "Hello"

TypeError: can't multiply sequence by non-int of type 'str'

In [60]:
"15" + 2

TypeError: can only concatenate str (not "int") to str

In [1]:
fruit = "banana"
baked_good = " nut bread"
print(fruit + baked_good)

banana nut bread


In [2]:
name = input("Please enter your name: ")

Please enter your name: Wen


In [3]:
response = input("What is your radius? ")
r = float(response)
area = 3.14159 * r**2
print("The area is ", area)

What is your radius? 3.14
The area is  30.974820764


In [4]:
r = float( input("What is your radius? ") )
print("The area is ", 3.14159 * r**2)

What is your radius? 5
The area is  78.53975


In [5]:
print("The area is ", 3.14159*float(input("What is your radius?"))**2)

What is your radius?5
The area is  78.53975


In [6]:
q = 7 // 3 # This is integer division operator
print(q)

2


In [7]:
r = 7 % 3
print(r)

1


In [8]:
total_secs = int(input("How many seconds, in total?"))
hours = total_secs // 3600
secs_still_remaining = total_secs % 3600
minutes = secs_still_remaining // 60
secs_finally_remaining = secs_still_remaining % 60
print("Hrs=", hours, " mins=", minutes,
"secs=", secs_finally_remaining)

How many seconds, in total?4
Hrs= 0  mins= 0 secs= 4


In [9]:
number = number + 1

NameError: name 'number' is not defined

In [11]:
import turtle # Allows us to use turtles
window = turtle.Screen() # Creates a playground for turtles
alex = turtle.Turtle() # Create a turtle, assign to alex
alex.forward(50) # Tell alex to move forward by 50 units
alex.left(90) # Tell alex to turn by 90 degrees
alex.forward(30) # Complete the second side of a rectangle
window.mainloop() # Wait for user to close window

Terminator: 

In [ ]:
import turtle
window = turtle.Screen()
window.bgcolor("lightgreen") # Set the window background color
window.title("Hello, Tess!") # Set the window title
tess = turtle.Turtle()
tess.color("blue") # Tell tess to change her color
tess.pensize(3) # Tell tess to set her pen width
tess.forward(50)
tess.left(120)
tess.forward(50) 
window.mainloop()

In [ ]:
import turtle
window = turtle.Screen() # Set up the window and its attributes
window.bgcolor("lightgreen")
window.title("Tess & Alex")
tess = turtle.Turtle() # Create tess and set some attributes
tess.color("hotpink")
tess.pensize(5)
alex = turtle.Turtle() # Create alex
tess.forward(80) # Make tess draw equilateral triangle
tess.left(120)
tess.forward(80)
tess.left(120)
tess.forward(80)
tess.left(120) # Complete the triangle
tess.right(180) # Turn tess around
tess.forward(80) # Move her away from the origin
alex.forward(50) # Make alex draw a square
alex.left(90)
alex.forward(50)
alex.left(90)
alex.forward(50)
alex.left(90)
alex.forward(50)
alex.left(90)
window.mainloop()

In [1]:
for friend in ["Joe", "Zoe", "Zuki", "Thandi", "Paris"]:
    invite = "Hi " + friend + ". Please come to my party!"
    print(invite)

Hi Joe. Please come to my party!
Hi Zoe. Please come to my party!
Hi Zuki. Please come to my party!
Hi Thandi. Please come to my party!
Hi Paris. Please come to my party!


In [10]:
import turtle
alex = turtle.Turtle()
for i in [0,1,2,3]:
    alex.forward(50)
    alex.left(90)

In [3]:
for i in range(4):
for x in range(10):

IndentationError: expected an indented block (<ipython-input-3-725727a4524e>, line 2)

In [11]:
for _ in range(4):
    alex.forward(50)
    alex.left(90)

In [12]:
for color in ["yellow", "red", "purple", "blue"]:
    alex.color(color)
    alex.forward(50)
    alex.left(90)

In [13]:
colors = ["yellow", "red", "purple", "blue"]
for color in colors:
    alex.color(color)
    alex.forward(50)
    alex.left(90)

In [14]:
alex.penup()
alex.forward(100) # This moves alex, but no line is drawn
alex.pendown()

In [15]:
alex.shape("turtle")

In [19]:
alex.speed(1)

In [57]:
import turtle
window = turtle.Screen()
window.bgcolor("lightgreen")
tess = turtle.Turtle()
tess.shape("turtle")
tess.color("blue")

tess.penup() # This is new
size = 20
for _ in range(30):
    tess.stamp() # Leave an impression on the canvas
    size = size + 2 # Increase the size on every iteration
    tess.forward(size) # Move tess along
    tess.right(24) # ... and turn her

window.mainloop()

In [2]:
type(True)

bool

In [7]:
type(true)

NameError: name 'true' is not defined

In [8]:
>>> 5 == (3 + 2)

True

In [9]:
>>> 5 == 6

False

In [10]:
>>> j = "hel"
>>> j + "lo" == "hello"

True

In [13]:
>>> age = 19
>>> old_enough_to_get_driving_licence = age >= 18
>>> print(old_enough_to_get_driving_licence)

True


In [14]:
>>> type(old_enough_to_get_driving_licence)

bool

In [16]:
x and False == False

NameError: name 'x' is not defined

In [58]:
x = int( input ("x =") );
if x % 2 == 0:
    print(x, " is even.")
    print("Did you know that 2 is the only even number that is prime?")
else:
    print(x, " is odd.")
    print("Did you know that multiplying two odd numbers " + 
                                   "always gives an odd result?")

x =5
5  is odd.
Did you know that multiplying two odd numbers always gives an odd result?


In [62]:
if True: # This is always True,
    pass # so this is always executed, but it does nothing
else:
    pass # And this is never executed

In [66]:
if x < 0:
    print("The negative number ", x, " is not valid here.")
    x = 42
    print("I've decided to use the number 42 instead.")
print("The square root of ", x, "is", math.sqrt(x))

NameError: name 'math' is not defined

In [68]:
if 0 < x: # Assume x is an int here
    if x < 10:
        print("x is a positive single digit.")

x is a positive single digit.


In [70]:
if 0 < x and x < 10:
    print("x is a positive single digit.")

x is a positive single digit.


In [71]:
if 0 < x < 10:
    print("x is a positive single digit.")

x is a positive single digit.


In [73]:
if not (age >= 18):
    print("Hey, you're too young to get a driving licence!")

In [74]:
if age < 18:
    print("Hey, you're too young to get a driving licence!")

In [75]:
if not (sword_charge >= 0.90 and shield_energy >= 100):
    print("Your attack has no effect, the dragon fries you to a crisp!")
else:
    print("The dragon crumples in a heap. You rescue the gorgeous princess!")

NameError: name 'sword_charge' is not defined

In [76]:
if sword_charge < 0.90 or shield_energy < 100:
    print("Your attack has no effect, the dragon fries you to a crisp!")
else:
    print("The dragon crumples in a heap. You rescue the gorgeous princess!")

NameError: name 'sword_charge' is not defined

In [77]:
if sword_charge >= 0.90 and shield_energy >= 100:
    print("The dragon crumples in a heap. You rescue the gorgeous princess!")
else:
    print("Your attack has no effect, the dragon fries you to a crisp!")

NameError: name 'sword_charge' is not defined

In [78]:
sword_check = sword_charge >= 0.90
shield_check = shield_energy >= 100

if sword_check and shield_check:
    print("The dragon crumples in a heap. You rescue the gorgeous princess!")
else:
    print("Your attack has no effect, the dragon fries you to a crisp!")

NameError: name 'sword_charge' is not defined

In [79]:
airtime_remaining = 15
print(airtime_remaining)
airtime_remaining = 7
print(airtime_remaining)

15
7


In [80]:
a = 5
b = a # After executing this line, a and b are now equal
a = 3 # After executing this line, a and b are no longer equal

In [81]:
n = 5
n = 3 * n + 1

In [84]:
w = x + 1

In [85]:
for friend in ["Joe", "Zoe", "Zuki", "Thandi", "Paris"]:
    invite = "Hi " + friend + ". Please come to my party!"
print(invite)

Hi Paris. Please come to my party!


In [86]:
numbers = [5, 6, 32, 21, 9]
running_total = 0
for number in numbers:
    running_total = running_total + number
print(running_total)

73


In [88]:
n = 6

current_sum = 0
i = 0
while i <= n:
    current_sum += i
    i += 1
print(current_sum)

21


In [89]:
n = 1027371

while n != 1:
    print(n, end=", ")
    if n % 2 == 0: # n is even
        n = n // 2
    else: # n is odd
        n = n * 3 + 1
print(n, end=".\n")

1027371, 3082114, 1541057, 4623172, 2311586, 1155793, 3467380, 1733690, 866845, 2600536, 1300268, 650134, 325067, 975202, 487601, 1462804, 731402, 365701, 1097104, 548552, 274276, 137138, 68569, 205708, 102854, 51427, 154282, 77141, 231424, 115712, 57856, 28928, 14464, 7232, 3616, 1808, 904, 452, 226, 113, 340, 170, 85, 256, 128, 64, 32, 16, 8, 4, 2, 1.


In [90]:
n = 3029
count = 0
while n != 0:
    count = count + 1
    n = n // 10
print(count)

4


In [91]:
n = 2574301453
count = 0 
while n > 0:
    digit = n % 10
    if digit == 0 or digit == 5:
        count = count + 1
    n = n // 10
print(count)

3


In [94]:
for x in range(13): # Generate numbers 0 to 12
    print(x, "\t", 2**x)

0 	 1
1 	 2
2 	 4
3 	 8
4 	 16
5 	 32
6 	 64
7 	 128
8 	 256
9 	 512
10 	 1024
11 	 2048
12 	 4096


In [95]:
for i in range(1, 7):
    print(2 * i, end=" ")
print()

2 4 6 8 10 12 


In [96]:
for i in [12, 16, 17, 24, 29]:
    if i % 2 == 1: # If the number is odd
        break # ... immediately exit the loop
    print(i)
print("done")

12
16
done


In [99]:
total = 0
while True:
    response = input("Enter the next number. (Leave blank to end)")
    if response == "" or response == "-1":
        break
total += int(response)
print("The total of the numbers you entered is ", total)

Enter the next number. (Leave blank to end)15
Enter the next number. (Leave blank to end)13
Enter the next number. (Leave blank to end)-1
The total of the numbers you entered is  -1


In [100]:
while True:
    play_the_game_once()
    response = input("Play again? (yes or no)")
    if response != "yes":
        break
print("Goodbye!")

NameError: name 'play_the_game_once' is not defined

In [ ]:
import random # We cover random numbers in the
rng = random.Random() # modules chapter, so peek ahead if you˓→want. "rng" stands for "random number generator".
number = rng.randrange(1, 1000) # Get random number between [1 and 1000).

guesses = 0
message = ""

while True:
    guess = int(input(message + "\nGuess my number between 1 and 1000: "))
    guesses += 1
    if guess > number:
        message += str(guess) + " is too high.\n"
    elif guess < number:
        message += str(guess) + " is too low.\n"
    else:
        break
input("\n\nGreat, you got it in "+str(guesses)+" guesses!\n\n")


Guess my number between 1 and 1000: 863
863 is too high.

Guess my number between 1 and 1000: 500
863 is too high.
500 is too high.

Guess my number between 1 and 1000: 300
863 is too high.
500 is too high.
300 is too high.

Guess my number between 1 and 1000: 200
863 is too high.
500 is too high.
300 is too high.
200 is too high.

Guess my number between 1 and 1000: 150
863 is too high.
500 is too high.
300 is too high.
200 is too high.
150 is too low.

Guess my number between 1 and 1000: 160
863 is too high.
500 is too high.
300 is too high.
200 is too high.
150 is too low.
160 is too high.

Guess my number between 1 and 1000: 155
863 is too high.
500 is too high.
300 is too high.
200 is too high.
150 is too low.
160 is too high.
155 is too high.

Guess my number between 1 and 1000: 154
863 is too high.
500 is too high.
300 is too high.
200 is too high.
150 is too low.
160 is too high.
155 is too high.
154 is too high.

Guess my number between 1 and 1000: 153
863 is too high.
500 is

In [3]:
for i in [12, 16, 17, 24, 29, 30]:
    if i % 2 == 1: # If the number is odd
        continue # Don't process it
    print(i)
print("done")

12
16
24
30
done


In [4]:
year_born = ("Paris Hilton", 1981)
celebs = [("Brad Pitt", 1963), ("Jack Nicholson", 1937),
                               ("Justin Bieber", 1994)]
print(celebs)
print(len(celebs))

[('Brad Pitt', 1963), ('Jack Nicholson', 1937), ('Justin Bieber', 1994)]
3


In [6]:
for name, year in celebs:
    if year < 1980:
         print(name)

Brad Pitt
Jack Nicholson


In [2]:
students = [
   ("John", ["CompSci", "Physics"]),
   ("Vusi", ["Maths", "CompSci", "Stats"]),
   ("Jess", ["CompSci", "Accounting", "Economics", "Management"]),
   ("Sarah", ["InfSys", "Accounting", "Economics", "CommLaw"]),
   ("Zuki", ["Sociology", "Economics", "Law", "Stats", "Music"])]
for name, subjects in students:
    print(name, "takes", len(subjects), "courses")

John takes 2 courses
Vusi takes 3 courses
Jess takes 4 courses
Sarah takes 4 courses
Zuki takes 5 courses


In [9]:
counter = 0
for name, subjects in students:
    for s in subjects: # A nested loop!
        if s == "CompSci":
            counter += 1
print("The number of students taking CompSci is", counter)

The number of students taking CompSci is 3


In [11]:
counter = 0
for name, subjects in students:
    if "CompSci" in subjects:
        counter += 1

In [7]:
threshold = 0.001
if abs(a-b) < threshold: # Make this smaller for better accuracy
    break

SyntaxError: 'break' outside loop (<ipython-input-7-0098e50e7b5d>, line 6)

In [3]:
n = 8
threshold = 0.001
approximation = n/2 # Start with some or other guess at the answer
while True:
    better = (approximation + n/approximation)/2
    if abs(approximation - better) < threshold:
        print(better)
        break
    approximation = better

2.8284271247493797


In [5]:
numbers = [10, 5, 24, 8, 6]
 # Buggy version
for number in numbers:
    if number % 2 == 1:
        print(True)
        break
    else:
        print(False)
        break

False


In [9]:
numbers = [10, 5, 24, 8, 6]
count = 0
for number in numbers:
    if number % 2 == 1:
       count += 1 # Count the odd numbers
if count > 0:
    print(True)
else:
    print(False)

True


In [10]:
numbers = [10, 5, 24, 8, 6]
count = 0
for number in numbers:
    if number % 2 == 1:
        count += 1 # Count the odd numbers
print(count > 0) # Aha! a programmer who understands that Boolean
  # expressions are not just used in if statements!

True


In [11]:
numbers = [10, 5, 24, 8, 6]
count = 0
for number in numbers:
    count += number % 2 == 1
print(count > 0) # Aha! a programmer who understands that Boolean
  # expressions are not just used in if statements!

True


In [1]:
import random
joe = random.Random()
# Version 1
# Build a list of random numbers, then sum them
numbers = []
for _ in range(10000000):
    num = joe.randrange(1000) # Generate one random number
    numbers.append(num) # Save it in our list, see the next˓→chapter
tot = sum(numbers)
print(tot)

4994868341


In [3]:
# Version 2
 # Sum the random numbers as we generate them
tot = 0
for _ in range(10000000):
    num = joe.randrange(1000)
    tot += num
print(tot)

4994918675


In [ ]:
import turtle

def draw_square(animal, size):
    """
    Make animal draw a square with sides of length size.
    """
    for _ in range(4):
        animal.forward(size)
        animal.left(90)


window = turtle.Screen() # Set up the window and its attributes
window.bgcolor("lightgreen")
window.title("Alex meets a function")

alex = turtle.Turtle() # Create alex
draw_square(alex, 50) # Call the function to draw the square
window.mainloop()

In [ ]:
import turtle

def draw_multicolor_square(animal, size):
    """Make animal draw a multi-color square of given size."""
    for color in ["red", "purple", "hotpink", "blue"]:
        animal.color(color)
        animal.forward(size)
        animal.left(90)

window = turtle.Screen() # Set up the window and its attributes
window.bgcolor("lightgreen")

tess = turtle.Turtle() # Create tess and set some attributes
tess.pensize(3)

size = 20 # Size of the smallest square
for _ in range(15):
    draw_multicolor_square(tess, size)
    size += 10 # Increase the size for next time
    tess.forward(10) # Move tess along a little
    tess.right(18) # and give her some turn
window.mainloop()

In [ ]:
def draw_rectangle(animal, width, height):
 """Get animal to draw a rectangle of given width and height."""
     for _ in range(2):
        animal.forward(width)
        animal.left(90)
        animal.forward(height)
        animal.left(90)

In [ ]:
def draw_square(animal, size): # A new version of draw_square
    draw_rectangle(animal, size, size)

In [ ]:
import turtle

def draw_square(animal, size):
    for _ in range(4):
        animal.forward(size)
        animal.left(90)

window = turtle.Screen() # Set up the window and its attributes

tess = turtle.Turtle() # Create tess and set some attributes

draw_square(tess, 50)

window.mainloop()

In [1]:
abs(5)

5

In [2]:
abs(-5)

5

In [3]:
pow(2, 3)

8

In [4]:
pow(7, 4)

2401

In [5]:
max(7, 11)

11

In [6]:
max(4, 1, 17, 2, 12)

17

In [7]:
max(3 * 11, 5**3, 512 - 9, 1024**0)

503

In [8]:
biggest = max(3, 7, 2, 5)
x = abs(3 - 11) + 10

In [11]:
def final_amount(p, r, n, t):
    """
    Apply the compound interest formula to p
    to produce the final amount.
    """

    a = p * (1 + r/n) ** (n*t)
    return a # This is new, and makes the function fruitful.
 # now that we have the function above, let us call it.
toInvest = float(input("How much do you want to invest?"))
fnl = final_amount(toInvest, 0.08, 12, 5)
print("At the end of the period you'll have", fnl)

How much do you want to invest?800
At the end of the period you'll have 1191.876566641284


In [12]:
def final_amount_v2(principal_amount, nominal_percentage_rate,
                                    num_times_per_year, years):
    a = principal_amount * (1 + nominal_percentage_rate /
                          num_times_per_year) ** (num_times_per_year*years)
    return a

def final_amount_v3(amount, rate, compounded, years):
    a = amount * (1 + rate/compounded) ** (componded*years)
    return a

def final_amount_v4(amount, rate, compounded, years):
    """
    The a in final_amount_v3 was a useless asignment.
    We might as well skip it.
    """
    return amount * (1 + rate/compounded) ** (componded*years)

In [13]:
def final_amount(p, r, n, t):
    a = p * (1 + r/n) ** (n*t)
    return a

In [14]:
a

NameError: name 'a' is not defined

In [15]:
import turtle

def make_window(color, title):
    """
      Set up the window with the given background color and title.
      Returns the new window.
    """
    window = turtle.Screen()
    window.bgcolor(color)
    window.title(title)
    return window
def make_turtle(color, size):

    """
    Set up a turtle with the given color and pensize.
    Returns the new turtle.
    """
    animal = turtle.Turtle()
    animal.color(color)
    animal.pensize(size)
    return animal


wn = make_window("lightgreen", "Tess and Alex dancing")
tess = make_turtle("hotpink", 5)
alex = make_turtle("black", 1)
dave = make_turtle("yellow", 2)

In [16]:
biggest = max(3, 7, 2, 5)
x = abs(3 - 11) + 10

In [19]:
def area(radius):
    b = 3.14159 * radius**2
    return b

In [20]:
def area(radius):
    return 3.14159 * radius * radius

In [21]:
def absolute_value(x):
    if x < 0:
        return -x
    else:
        return x

In [22]:
def absolute_value(x):
    if x < 0:
        return -x
    return x

In [23]:
def bad_absolute_value(x):
    if x < 0:
        return -x
    elif x > 0:
        return x

In [24]:
print(bad_absolute_value(0))

None


In [25]:
def find_first_2_letter_word(words):
    for word in words:
        if len(word) == 2:
            return word
    return ""

In [26]:
find_first_2_letter_word(["This", "is", "a", "dead", "parrot"])

'is'

In [27]:
find_first_2_letter_word(["I", "like", "cheese"])

''

In [28]:
def distance(x1, y1, x2, y2):
    return 0.0

In [29]:
distance(1, 2, 4, 6)

0.0

In [30]:
def distance(x1, y1, x2, y2):
    dx = x2 - x1
    dy = y2 - y1
    return 0.0

In [31]:
def distance(x1, y1, x2, y2):
    dx = x2 - x1
    dy = y2 - y1
    dsquared = dx*dx + dy*dy
    return 0.0

In [32]:
def distance(x1, y1, x2, y2):
    dx = x2 - x1
    dy = y2 - y1
    dsquared = dx*dx + dy*dy
    result = dsquared**0.5
    return result

In [33]:
import math

def distance(x1, y1, x2, y2):
    return math.sqrt( (x2-x1)**2 + (y2-y1)**2 )
distance(1, 2, 4, 6)

5.0

In [36]:
radius = distance(xc, yc, xp, yp)

NameError: name 'xc' is not defined

In [37]:
result = area(radius)
return result

NameError: name 'radius' is not defined

In [39]:
def area_of_circle(xc, yc, xp, yp):
    radius = distance(xc, yc, xp, yp)
    result = area(radius)
    return result

In [40]:
def area_of_circle(xc, yc, xp, yp):
    return area(distance(xc, yc, xp, yp))

In [41]:
def is_divisible(x, y):
    """ Test if x is exactly divisible by y """
    if x % y == 0:
        return True
    else:
        return False

In [42]:
def is_divisible(x, y):
    return x % y == 0

In [43]:
is_divisible(6, 4)

False

In [44]:
is_divisible(6, 3)

True

In [45]:
if is_divisible(x, y):
 ... # Do something ...
else:
 ... # Do something else ...

NameError: name 'y' is not defined

In [46]:
if is_divisible(x, y) == True:

SyntaxError: unexpected EOF while parsing (<ipython-input-46-e49d56ccdaee>, line 1)

In [50]:
def double_stuff(values):
    """ Return a new list which contains
        doubles of the elements in the list values.
    """
    new_list = []
    for value in values:
        new_elem = 2 * value
        new_list.append(new_elem)
 
    return new_list

In [51]:
things = [2, 5, 9] 
more_things = double_stuff(things)
things

[2, 5, 9]

In [52]:
more_things

[4, 10, 18]

In [53]:
things = [2, 5, 9]
things = double_stuff(things)
things

[4, 10, 18]

In [54]:
def double_stuff(values):
    """ Double the elements of values in-place. """
    for index, value in enumerate(values):
        values[index] = 2 * value

In [55]:
things = [2, 5, 9]
more_things = double_stuff(things)
things

[4, 10, 18]

In [57]:
more_things

In [61]:
def any_odd(xs): # Buggy version
 """ Return True if there is an odd number in xs, a list of integers. """
     for v in xs:
         if v % 2 == 1:
            return True
         else:
            return False

IndentationError: unexpected indent (<ipython-input-61-636b6536a38d>, line 3)

In [ ]:
def any_odd(xs):
 """ Return True if there is an odd number in xs, a list of integers. """
    for v in xs:
        if v % 2 == 1:
            return True
    return False

In [68]:
def any_odd(xs):
  """ Return True if there is an odd number in xs, a list of integers. """
    count = 0
    for v in xs:
    if v % 2 == 1:
    count += 1 # Count the odd numbers
    return count > 0

IndentationError: unexpected indent (<ipython-input-68-05ef9b58c63a>, line 3)

In [67]:
def any_odd(xs):
    """ Return True if there is an odd number in xs, a list of integers. """
    count = 0
    for v in xs:
        if v % 2 == 1:
            count += 1 # Count the odd numbers
    return count > 0 # Aha! a programmer who understands that Boolean
 # expressions are not just used in if statements!

In [70]:
sz = 2
def h2():
   """ Draw the next step of a spiral on each call. """
    global sz
    tess.turn(42)
    tess.forward(sz)
    sz += 1

IndentationError: unexpected indent (<ipython-input-70-c3cc45bb51db>, line 4)

In [71]:
if s.find("snake") >= 0: ...
if "snake" in s: ... # Also works, nice-to-know sugar coating!

NameError: name 's' is not defined

In [74]:
s = "..." # Get the next line from somewhere
def_pos = s.find("def ") # Look for "def " in the line
if def_pos == 0: # If it occurs at the left margin
    op_index = s.find("(") # Find the index of the open parenthesis
    fnname = s[4:op_index] # Slice out the function name
    print(fnname)

In [1]:
import random
joe = random.Random()

def sum1():
    """ Build a list of random numbers, then sum them """
    xs = []
    for i in range(10000000):
        num = joe.randrange(1000) # Generate one random number
        xs.append(num) # Save it in our list

    tot = sum(xs)
    return tot

def sum2():
    """ Sum the random numbers as we generate them """
    tot = 0
    for i in range(10000000):
        num = joe.randrange(1000)
        tot += num
    return tot
 
print(sum1())
print(sum2())

4996326442
4996098098


In [2]:
our_string = "Hello, World!"
all_caps = our_string.upper()
all_caps

'HELLO, WORLD!'

In [3]:
our_string = "Hello, World!"
new_string = our_string.

SyntaxError: invalid syntax (<ipython-input-3-b61acceabb0e>, line 2)

In [4]:
fruit = "banana"
letter = fruit[1]
print(letter)

a


In [5]:
letter = fruit[0]
print(letter)

b


In [6]:
fruit = "banana"
list(enumerate(fruit))

[(0, 'b'), (1, 'a'), (2, 'n'), (3, 'a'), (4, 'n'), (5, 'a')]

In [7]:
prime_numbers = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]
prime_numbers[4]

11

In [8]:
friends = ["Joe", "Zoe", "Brad", "Angelina", "Zuki", "Thandi", "Paris"]
friends[3]

'Angelina'

In [9]:
word = "banana"
len(word)

6

In [10]:
size = len(word)
last = word[size]

IndexError: string index out of range

In [11]:
size = len(word)
last = word[size-1]

In [12]:
ix = 0
while ix < len(fruit):
    letter = fruit[ix]
    print(letter)
    ix += 1

b
a
n
a
n
a


In [13]:
word="Banana"
for letter in word:
    print(letter)

B
a
n
a
n
a


In [14]:
prefixes = "JKLMNOPQ"
suffix = "ack"

for p in prefixes:
    print(p + suffix)

Jack
Kack
Lack
Mack
Nack
Oack
Pack
Qack


In [15]:
phrase = "Pirates of the Caribbean"
print(phrase[0:7])

Pirates


In [17]:
print(phrase[11:14])

the


In [18]:
print(phrase[13:24])

e Caribbean


In [19]:
friends = ["Joe", "Zoe", "Brad", "Angelina", "Zuki", "Thandi", "Paris"]
print(friends[2:4])

['Brad', 'Angelina']


In [20]:
word = "banana"
word[:3]

'ban'

In [21]:
word[3:]

'ana'

In [22]:
word[3:999]

'ana'

In [24]:
if word == "banana":
    print("Yes, we have no bananas!")

Yes, we have no bananas!


In [25]:
if word < "banana":
    print("Your word, " + word + ", comes before banana.")
elif word > "banana":
    print("Your word, " + word + ", comes after banana.")
else:
    print("Yes, we have no bananas!")

Yes, we have no bananas!


In [26]:
greeting = "Hello, world!"
greeting[0] = 'J' # ERROR!
print(greeting)

TypeError: 'str' object does not support item assignment

In [27]:
greeting = "Hello, world!"
new_greeting = "J" + greeting[1:]
print(new_greeting)

Jello, world!


In [28]:
"p" in "apple"

True

In [29]:
"i" in "apple"

False

In [30]:
"ap" in "apple"

True

In [31]:
"pa" in "apple"

False

In [32]:
"a" in "a"

True

In [33]:
"apple" in "apple"

True

In [34]:
"" in "a"

True

In [35]:
"" in "apple"

True

In [36]:
"x" not in "apple"

True

In [37]:
def remove_vowels(phrase):
    vowels = "aeiou"
    string_sans_vowels = ""
    for letter in phrase:
        if letter.lower() not in vowels:
            string_sans_vowels += letter
    return string_sans_vowels

In [38]:
def my_find(haystack, needle):
    """
    Find and return the index of needle in haystack.
    Return -1 if needle does not occur in haystack.
    """
    for index, letter in enumerate(haystack):
        if letter == needle:
            return index
    return -1

In [39]:
haystack = "Bananarama!"
print(haystack.find('a'))
print(my_find(haystack,'a'))

1
1


In [40]:
def count_a(text):
    count = 0
    for letter in text:
        if letter == "a":
            count += 1
    return(count)
 
print(count_a("banana") == 3)

True


In [71]:
def find2(haystack, needle, start):
     for index,letter in enumerate (haystack[start:])
         if letter == needle:
            return index + start
return -1




print(find2("banana", "a", 2) == 3)

SyntaxError: invalid syntax (<ipython-input-71-83b8dfb24077>, line 2)

In [62]:
def find(haystack, needle, start=0):
    for index,letter in enumerate(haystack[start:]):
        if letter == needle:
            return index + start
    return -1

In [72]:
def find(haystack, needle, start=0, end=-1):
    for index,letter in enumerate(haystack[start:end])
        if letter == needle:
            return index + start
    return -1

SyntaxError: invalid syntax (<ipython-input-72-8553ff6111ad>, line 2)

In [73]:
"banana".find("nan")

2

In [74]:
"banana".find("na", 3)

4

In [75]:
phrase = "Well I never did said Alice"
words = phrase.split()
words

['Well', 'I', 'never', 'did', 'said', 'Alice']

In [76]:
punctuation = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"

def remove_punctuation(phrase):
    phrase_sans_punct = ""
    for letter in phrase:
        if letter not in punctuation:
            phrase_sans_punct += letter
    return phrase_sans_punct

In [77]:
my_story = """
Pythons are constrictors, which means that they will 'squeeze' the life
out of their prey. They coil themselves around their prey and with
each breath the creature takes the snake will squeeze a little tighter
until they stop breathing completely. Once the heart stops the prey
is swallowed whole. The entire animal is digested in the snake's
stomach except for fur or feathers. What do you think happens to the fur,
feathers, beaks, and eggshells? The 'extra stuff' gets passed out as ---
you guessed it --- snake POOP! """

words = remove_punctuation(my_story).split()
print(words)

['Pythons', 'are', 'constrictors', 'which', 'means', 'that', 'they', 'will', 'squeeze', 'the', 'life', 'out', 'of', 'their', 'prey', 'They', 'coil', 'themselves', 'around', 'their', 'prey', 'and', 'with', 'each', 'breath', 'the', 'creature', 'takes', 'the', 'snake', 'will', 'squeeze', 'a', 'little', 'tighter', 'until', 'they', 'stop', 'breathing', 'completely', 'Once', 'the', 'heart', 'stops', 'the', 'prey', 'is', 'swallowed', 'whole', 'The', 'entire', 'animal', 'is', 'digested', 'in', 'the', 'snakes', 'stomach', 'except', 'for', 'fur', 'or', 'feathers', 'What', 'do', 'you', 'think', 'happens', 'to', 'the', 'fur', 'feathers', 'beaks', 'and', 'eggshells', 'The', 'extra', 'stuff', 'gets', 'passed', 'out', 'as', 'you', 'guessed', 'it', 'snake', 'POOP']


In [79]:
phrase = "His name is {0}!".format("Arthur")
print(phrase)

name = "Alice"
age = 10
phrase = "I am {1} and I am {0} years old.".format(age, name)
print(phrase)
phrase = "I am {0} and I am {1} years old.".format(age, name)
print(phrase)

x = 4
y = 5
phrase = "2**10 = {0} and {1} * {2} = {3:f}".format(2**10, x, y, x * y)
print(phrase)

His name is Arthur!
I am Alice and I am 10 years old.
I am 10 and I am Alice years old.
2**10 = 1024 and 4 * 5 = 20.000000


In [82]:
name1 = "Paris"
name2 = "Whitney"
name3 = "Hilton"

print("Pi to three decimal places is {0:.3f}".format(3.1415926))
print("123456789 123456789 123456789 123456789 123456789 123456789")
print("|||{0:<15}|||{1:^15}|||{2:>15}|||Born in {3}|||"
        .format(name1,name2,name3,1981))
print("The decimal value {0} converts to hex value {0:x}"
        .format(123456))

Pi to three decimal places is 3.142
123456789 123456789 123456789 123456789 123456789 123456789
|||Paris          |||    Whitney    |||         Hilton|||Born in 1981|||
The decimal value 123456 converts to hex value 1e240


In [83]:
letter = """
Dear {0} {2}.
 {0}, I have an interesting money-making proposition for you!
 If you deposit $10 million into my bank account, I can
 double your money ...
"""

print(letter.format("Paris", "Whitney", "Hilton"))
print(letter.format("Bill", "Henry", "Gates"))


Dear Paris Hilton.
 Paris, I have an interesting money-making proposition for you!
 If you deposit $10 million into my bank account, I can
 double your money ...


Dear Bill Gates.
 Bill, I have an interesting money-making proposition for you!
 If you deposit $10 million into my bank account, I can
 double your money ...



In [85]:
"hello {3}".format("Dave")

IndexError: tuple index out of range

In [86]:
print("i\ti**2\ti**3\ti**5\ti**10\ti**20")
for i in range(1, 11):
    print(i, "\t", i**2, "\t", i**3, "\t", i**5, "\t",
                                           i**10, "\t", i**20)

i	i**2	i**3	i**5	i**10	i**20
1 	 1 	 1 	 1 	 1 	 1
2 	 4 	 8 	 32 	 1024 	 1048576
3 	 9 	 27 	 243 	 59049 	 3486784401
4 	 16 	 64 	 1024 	 1048576 	 1099511627776
5 	 25 	 125 	 3125 	 9765625 	 95367431640625
6 	 36 	 216 	 7776 	 60466176 	 3656158440062976
7 	 49 	 343 	 16807 	 282475249 	 79792266297612001
8 	 64 	 512 	 32768 	 1073741824 	 1152921504606846976
9 	 81 	 729 	 59049 	 3486784401 	 12157665459056928801
10 	 100 	 1000 	 100000 	 10000000000 	 100000000000000000000


In [88]:
layout = "{0:>4}{1:>6}{2:>6}{3:>8}{4:>13}{5:>24}"

print(layout.format("i", "i**2", "i**3", "i**5", "i**10", "i**20"))
for i in range(1, 11):
    print(layout.format(i, i**2, i**3, i**5, i**10, i**20))

   i  i**2  i**3    i**5        i**10                   i**20
   1     1     1       1            1                       1
   2     4     8      32         1024                 1048576
   3     9    27     243        59049              3486784401
   4    16    64    1024      1048576           1099511627776
   5    25   125    3125      9765625          95367431640625
   6    36   216    7776     60466176        3656158440062976
   7    49   343   16807    282475249       79792266297612001
   8    64   512   32768   1073741824     1152921504606846976
   9    81   729   59049   3486784401    12157665459056928801
  10   100  1000  100000  10000000000   100000000000000000000


In [1]:
year_born = ("Paris Hilton", 1981)

In [2]:
julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress", "Atlanta, Georgia")

In [3]:
julia[2]

1967

In [4]:
julia[0] = "X"

TypeError: 'tuple' object does not support item assignment

In [5]:
julia = julia[:3] + ("Eat Pray Love", 2010) + julia[5:]
julia

('Julia',
 'Roberts',
 1967,
 'Eat Pray Love',
 2010,
 'Actress',
 'Atlanta, Georgia')

In [6]:
tup = (5,)
type(tup)

tuple

In [7]:
x = (5)
type(x)

int

In [8]:
bob = ("Bob", 19, "CS")

In [9]:
bob = ("Bob", 19, "CS")
(name, age, studies) = bob # tuple unpacking
name

'Bob'

In [10]:
age

19

In [11]:
studies

'CS'

In [12]:
(one, two, three, four) = (1, 2, 3)

ValueError: not enough values to unpack (expected 4, got 3)

In [13]:
def circle_stats(r):
    """ Return (circumference, area) of a circle of radius r """
    circumference = 2 * math.pi * r
    area = math.pi * r * r
    return (circumference, area)

In [14]:
students = [
("John", ["CompSci", "Physics"]),
("Vusi", ["Maths", "CompSci", "Stats"]),
("Jess", ["CompSci", "Accounting", "Economics", "Management"]),
("Sarah", ["InfSys", "Accounting", "Economics", "CommLaw"]),
("Zuki", ["Sociology", "Economics", "Law", "Stats", "Music"])]

In [15]:
julia_more_info = ( ("Julia", "Roberts"), (8, "October", 1967),
"Actress", ("Atlanta", "Georgia"),
[ ("Duplicity", 2009),
("Notting Hill", 1999),
("Pretty Woman", 1990),
("Erin Brockovich", 2000),
("Eat Pray Love", 2010),
("Mona Lisa Smile", 2003),
("Oceans Twelve", 2004) ])

In [16]:
numbers = [10, 20, 30, 40]
words = ["spam", "bungee", "swallow"]

In [17]:
stuffs = ["hello", 2.0, 5, [10, 20]]

In [18]:
vocabulary = ["apple", "cheese", "dog"]
numbers = [17, 123]
an_empty_list = []
print(vocabulary, numbers, an_empty_list)

['apple', 'cheese', 'dog'] [17, 123] []


In [19]:
numbers[0]

17

In [20]:
numbers[9-8]

123

In [21]:
numbers[1.0]

TypeError: list indices must be integers or slices, not float

In [22]:
numbers[2]

IndexError: list index out of range

In [23]:
horsemen = ["war", "famine", "pestilence", "death"]

for i in [0, 1, 2, 3]:
    print(horsemen[i])

war
famine
pestilence
death


In [24]:
horsemen = ["war", "famine", "pestilence", "death"]

for h in horsemen:
    print(h)

war
famine
pestilence
death


In [25]:
horsemen = ["war", "famine", "pestilence", "death"]

for i in range(len(horsemen)):
    print(horsemen[i])

war
famine
pestilence
death


In [26]:
horsemen = ["war", "famine", "pestilence", "death"]

for horseman in horsemen:
    print horseman

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(horseman)? (<ipython-input-26-b4c598fec2f0>, line 4)

In [27]:
len(["car makers", 1, ["Ford", "Toyota", "BMW"], [1, 2, 3]])

4

In [29]:
horsemen = ["war", "famine", "pestilence", "death"]
"pestilence" in horsemen

True

In [30]:
"debauchery" in horsemen

False

In [31]:
"debauchery" not in horsemen

True

In [33]:
students = [
    ("John", ["CompSci", "Physics"]),
    ("Vusi", ["Maths", "CompSci", "Stats"]),
    ("Jess", ["CompSci", "Accounting", "Economics", "Management"]),
    ("Sarah", ["InfSys", "Accounting", "Economics", "CommLaw"]),
    ("Zuki", ["Sociology", "Economics", "Law", "Stats", "Music"])]
counter = 0
for name, subjects in students:
    if "CompSci" in subjects:
        counter += 1

print("The number of students taking CompSci is", counter)

The number of students taking CompSci is 3


In [34]:
first_list = [1, 2, 3]
second_list = [4, 5, 6]
both_lists = first_list + second_list
both_lists

[1, 2, 3, 4, 5, 6]

In [35]:
[0] * 4

[0, 0, 0, 0]

In [36]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [37]:
a_list = ["a", "b", "c", "d", "e", "f"]
a_list[1:3]

['b', 'c']

In [38]:
a_list[:4]

['a', 'b', 'c', 'd']

In [39]:
a_list[3:]

['d', 'e', 'f']

In [40]:
a_list[:]

['a', 'b', 'c', 'd', 'e', 'f']

In [41]:
fruit = ["banana", "apple", "quince"]
fruit[0] = "pear"
fruit[2] = "orange"
fruit

['pear', 'apple', 'orange']

In [42]:
my_string = "TEST"
my_string[2] = "X"

TypeError: 'str' object does not support item assignment

In [43]:
my_list = ["T", "E", "S", "T"]
my_list[2] = "X"
my_list

['T', 'E', 'X', 'T']

In [44]:
a_list = ["a", "b", "c", "d", "e", "f"]
a_list[1:3] = ["x", "y"]
a_list

['a', 'x', 'y', 'd', 'e', 'f']

In [45]:
a_list = ["a", "b", "c", "d", "e", "f"]
a_list[1:3] = []
a_list

['a', 'd', 'e', 'f']

In [46]:
a_list = ["a", "d", "f"]
a_list[1:1] = ["b", "c"]
a_list

['a', 'b', 'c', 'd', 'f']

In [47]:
a_list[4:4] = ["e"]
a_list

['a', 'b', 'c', 'd', 'e', 'f']

In [48]:
a = ["one", "two", "three"]
del a[1]
a

['one', 'three']

In [49]:
a_list = ["a", "b", "c", "d", "e", "f"]
del a_list[1:5]
a_list

['a', 'f']

In [50]:
a = "banana"
b = "banana"

In [51]:
a is b

True

In [52]:
a = [1, 2, 3]
b = [1, 2, 3]
a == b

True

In [53]:
a is b

False

In [54]:
a = [1, 2, 3]
b = a
a is b

True

In [55]:
b[0] = 5
a

[5, 2, 3]

In [56]:
a = [1, 2, 3]
b = a[:]
b

[1, 2, 3]

In [57]:
b[0] = 5
a

[1, 2, 3]

In [61]:
friends = ["Joe", "Zoe", "Brad", "Angelina", "Zuki", "Thandi", "Paris"]
for friend in friends:
    print(friend)

Joe
Zoe
Brad
Angelina
Zuki
Thandi
Paris


In [62]:
for number in range(20):
    if number % 3 == 0:
        print(number)

for fruit in ["banana", "apple", "quince"]:
    print("I like to eat " + fruit + "s!")

0
3
6
9
12
15
18
I like to eat bananas!
I like to eat apples!
I like to eat quinces!


In [63]:
xs = [1, 2, 3, 4, 5]

for i in range(len(xs)):
    xs[i] = xs[i]**2

In [64]:
xs = [1, 2, 3, 4, 5]

for (i, val) in enumerate(xs):
    xs[i] = val**2

In [65]:
for (i, v) in enumerate(["banana", "apple", "pear", "lemon"]):
    print(i, v)

0 banana
1 apple
2 pear
3 lemon


In [2]:
def double_stuff(stuff_list):
    """ Overwrite each element in a_list with double its value. """
    for (index, stuff) in enumerate(stuff_list):
        stuff_list[index] = 2 * stuff

In [3]:
things = [2, 5, 9]
double_stuff(things)
print(things)

[4, 10, 18]


In [68]:
mylist = []
mylist.append(5)
mylist.append(27)
mylist.append(3)
mylist.append(12)
mylist

[5, 27, 3, 12]

In [69]:
mylist.insert(1, 12) # Insert 12 at pos 1, shift other items up
mylist

[5, 12, 27, 3, 12]

In [70]:
mylist.count(12)

2

In [72]:
mylist.extend([5, 9, 5, 11])
mylist

[5, 12, 27, 3, 12, 5, 9, 5, 11, 5, 9, 5, 11]

In [73]:
mylist.index(9)

6

In [74]:
mylist.reverse()
mylist

[11, 5, 9, 5, 11, 5, 9, 5, 12, 3, 27, 12, 5]

In [76]:
mylist.sort()
mylist

[3, 5, 5, 5, 5, 5, 9, 9, 11, 11, 12, 12, 27]

In [77]:
mylist.remove(12) # Remove the first 12 in the list
mylist

[3, 5, 5, 5, 5, 5, 9, 9, 11, 11, 12, 27]

In [84]:
def double_stuff(a_list):
    """ Return a new list which contains
        doubles of the elements in a_list.
    """
    new_list = []
    for value in a_list:
        new_elem = 2 * value
        new_list.append(new_elem)
 
    return new_list

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 10)

In [4]:
things = [2, 5, 9]
more_things = double_stuff(things)
things

[4, 10, 18]

In [5]:
more_things 

In [6]:
things = [2, 5, 9]
things = double_stuff(things)
things

In [12]:
initialize a result variable to be an empty list
loop
    create a new element
    append it to result
return the result

SyntaxError: invalid syntax (<ipython-input-12-486305419c39>, line 1)

In [8]:
def primes_lessthan(n):
    """ Return a list of all prime numbers less than n. """
    result = []
    for i in range(2, n):
        if is_prime(i):
            result.append(i)
    return result

In [13]:
song = "The rain in Spain..."
words = song.split()
words

['The', 'rain', 'in', 'Spain...']

In [14]:
song.split("ai")

['The r', 'n in Sp', 'n...']

In [15]:
glue = ";"
phrase = glue.join(words)
phrase

'The;rain;in;Spain...'

In [16]:
" --- ".join(words)

'The --- rain --- in --- Spain...'

In [17]:
"".join(words)

'TheraininSpain...'

In [19]:
letters = list("Crunchy Frog")
letters

['C', 'r', 'u', 'n', 'c', 'h', 'y', ' ', 'F', 'r', 'o', 'g']

In [20]:
"".join(letters)

'Crunchy Frog'

In [21]:
def f(n):
    """ Find the first positive integer between 101 and less
        than n that is divisible by 21
    """
    for i in range(101, n):
        if (i % 21 == 0):
            return i


print(f(110) == 105)
print(f(1000000000) == 105)

True
True


In [22]:
range(10)

range(0, 10)

In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import random
joe = random.Random()

def sum1():
    """ Build a list of random numbers, then sum them """
    xs = []
    for i in range(10000000):
        num = joe.randrange(1000) # Generate one random number
        xs.append(num) # Save it in our list

    tot = sum(xs)
    return tot

def sum2():
    """ Sum the random numbers as we generate them """
    tot = 0  
    for i in range(10000000):
        num = joe.randrange(1000)
        tot += num
    return tot

print(sum1())
print(sum2())

4993568009
4995070094


In [3]:
nested = ["hello", 2.0, 5, [10, 20]]

In [4]:
print(nested[3])

[10, 20]


In [5]:
elem = nested[3]
elem[0]

10

In [6]:
nested[3][1]

20

In [9]:
mx = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
mx[1]

[4, 5, 6]

In [10]:
mx[1][2]

6

In [11]:
english_spanish = {}
english_spanish["one"] = "uno"
english_spanish["two"] = "dos"

In [12]:
print(english_spanish)

{'one': 'uno', 'two': 'dos'}


In [13]:
{"apples": 430, "bananas": 312, "oranges": 525, "pears": 217}

{'apples': 430, 'bananas': 312, 'oranges': 525, 'pears': 217}

In [14]:
[('apples', 430), ('bananas', 312), ('oranges', 525), ('pears', 217)]

[('apples', 430), ('bananas', 312), ('oranges', 525), ('pears', 217)]

In [15]:
english_spanish = {"one": "uno", "two": "dos", "three": "tres"}

In [16]:
print(english_spanish["two"])

dos


In [17]:
inventory = {"apples": 430, "bananas": 312, "oranges": 525, "pears": 217}
print(inventory)

{'apples': 430, 'bananas': 312, 'oranges': 525, 'pears': 217}


In [18]:
del inventory["bananas"]
print(inventory)

{'apples': 430, 'oranges': 525, 'pears': 217}


In [19]:
inventory["bananas"] = 0
print(inventory)

{'apples': 430, 'oranges': 525, 'pears': 217, 'bananas': 0}


In [20]:
inventory["bananas"] += 200
print(inventory)

{'apples': 430, 'oranges': 525, 'pears': 217, 'bananas': 200}


In [21]:
len(inventory)

4

In [22]:
for key in english_spanish.keys(): # The order of the k's is not defined
    print("Got key", key, "which maps to value", english_spanish[key])

keys = list(english_spanish.keys())
print(keys)

Got key one which maps to value uno
Got key two which maps to value dos
Got key three which maps to value tres
['one', 'two', 'three']


In [23]:
for key in english_spanish:
    print("Got key", key)

Got key one
Got key two
Got key three


In [24]:
list(english_spanish.values())

['uno', 'dos', 'tres']

In [25]:
list(english_spanish.items())

[('one', 'uno'), ('two', 'dos'), ('three', 'tres')]

In [26]:
for (key,value) in english_spanish.items():   
    print("Got",key,"that maps to",value)

Got one that maps to uno
Got two that maps to dos
Got three that maps to tres


In [27]:
"one" in english_spanish


True

In [28]:
"six" in english_spanish

False

In [29]:
"tres" in english_spanish

False

In [30]:
english_spanish["dog"]

KeyError: 'dog'

In [31]:
opposites = {"up": "down", "right": "wrong", "yes": "no"}
alias = opposites
copy = opposites.copy()

In [32]:
alias["right"] = "left"
opposites["right"]

'left'

In [33]:
copy["right"] = "privilege"
opposites["right"]

'left'

In [38]:
letter_counts = {}
for letter in "Mississippi":
     letter_counts[letter] = letter_counts.get(letter, 0) + 1
    
letter_counts

{'M': 1, 'i': 4, 's': 4, 'p': 2}

In [39]:
letter_items = list(letter_counts.items())
letter_items.sort()
print(letter_items)

[('M', 1), ('i', 4), ('p', 2), ('s', 4)]


In [40]:
a = [2, 3, 8]
2 * a

[2, 3, 8, 2, 3, 8]

In [41]:
a = [2, 3, 8]
2 * a
2.1 * a

TypeError: can't multiply sequence by non-int of type 'float'

In [42]:
values = [2, 3, 8]
result = []
for x in values:
    result.append(2.1 * x)

In [43]:
import numpy as np
a = np.array([2, 3, 8])
2.1 * a

array([ 4.2,  6.3, 16.8])

In [44]:
import numpy as np
a = np.array([2, 3, 8])
a * a

array([ 4,  9, 64])

In [45]:
a**2

array([ 4,  9, 64], dtype=int32)

In [47]:
a = np.array([2, 3, 8])
np.dot(a,a)

77

In [48]:
import numpy as np
a = np.array([2, 3, 8])
a.shape

(3,)

In [49]:
b = np.array([
    [2, 3, 8],
    [4, 5, 6],
    ])
b.shape

(2, 3)

In [50]:
a = np.array([2, 3, 8])
a[2]

8

In [51]:
a[1:]

array([3, 8])

In [52]:
b = np.array([
    [2, 3, 8],
    [4, 5, 6],
    ])
b[1]

array([4, 5, 6])

In [53]:
b[1][2]

6

In [54]:
b[:, 1]

array([3, 5])

In [55]:
a = np.array([230, 10, 284, 39, 76])
cutoff = 200
a > cutoff

array([ True, False,  True, False, False])

In [56]:
a = np.array([230, 10, 284, 39, 76])
cutoff = 200
a[a > cutoff] = 0
a

array([ 0, 10,  0, 39, 76])

In [57]:
a = np.array([230, 10, 284, 39, 76])
cutoff = 200
new_a = []
for x in a:
    if x > cutoff:
        new_a.append(0)
    else:
        new_a.append(x)
a = np.array(new_a)

In [58]:
a = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    ])
b = np.array([10, 100])
a * b

array([[  0, 100],
       [ 20, 300],
       [ 40, 500]])

In [59]:
c = np.array([
    [0, 1, 2],
    [3, 4, 5],
    ])
b = np.array([10, 100])
c * b

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [60]:
c = np.array([
[0, 1, 2],
[3, 4, 5],
])
b = np.array([10, 100])
c * b[:, None]

array([[  0,  10,  20],
       [300, 400, 500]])

In [61]:
import numpy as np
a = np.array([200], dtype='uint8')
a + a

array([144], dtype=uint8)

In [62]:
import numpy as np
a = np.array([200], dtype='uint16')
a + a

array([400], dtype=uint16)

In [63]:
import numpy as np
a = np.array([200], dtype='uint8')
a.astype('uint64')

array([200], dtype=uint64)

In [64]:
with open("test.txt", "w") as myfile:
    myfile.write("My first file written from Python\n")
    myfile.write("---------------------------------\n")
    myfile.write("Hello, world!\n")

In [67]:
with open("test.txt", "r") as my_new_handle:
     for the_line in my_new_handle:
     # Do something with the line we just read.
     # Here we just print it.
        print(the_line, end="")

My first file written from Python
---------------------------------
Hello, world!


In [68]:
mynewhandle = open("wharrah.txt", "r")

FileNotFoundError: [Errno 2] No such file or directory: 'wharrah.txt'

In [71]:
with open("friends.txt", "r") as input_file:
    all_lines = input_file.readlines()
all_lines.sort()

with open("sortedfriends.txt", "w") as output_file:
    for line in all_lines:
        outut_file.write(line)

FileNotFoundError: [Errno 2] No such file or directory: 'friends.txt'

In [72]:
with open("somefile.txt") as f:
    content = f.read()
words = content.split()
print("There are {0} words in the file.".format(len(words)))

FileNotFoundError: [Errno 2] No such file or directory: 'somefile.txt'

In [73]:
def filter(oldfile, newfile):
    with open(oldfile, "r") as infile, open(newfile, "w") as outfile:
        for line in infile:
            # Put any processing logic here
            if not line.startswith('#'):
                outfile.write(line)

In [74]:
wordsfile = open("/usr/share/dict/words", "r")
wordlist = wordsfile.readlines()
print(wordlist[:6])

FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/dict/words'

In [75]:
import urllib.request

url = "http://xml.resource.org/public/rfc/txt/rfc793.txt"
destination_filename = "rfc793.txt"

urllib.request.urlretrieve(url, destination_filename)

HTTPError: HTTP Error 404: Not Found

In [76]:
import requests

url = "http://xml.resource.org/public/rfc/txt/rfc793.txt"
response = requests.get(url)
print(response.text)

<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Object not found!</title>
<link rev="made" href="mailto:webmaster@tools.ietf.org" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Object not found!</h1>
<p>


    The requested URL was not found on this server.

  

    If you entered the URL manually please check your
    spelling and try again.

  

</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:webmaster@tools.ietf.org">webmaster</a>.

</p>

<h2>Error 404</h2>
<address>
  <a href="/">xml2rfc.tools.ietf.org</a><br />
  
  <span>Sat Sep 21 23:29:17 2019<br />
  Apache/2.2.

In [77]:
import requests

url = "http://xml.resource.org/public/rfc/txt/rfc793.txt"
response = requests.get(url)
for line in response:
    print(line)

b'<?xml version="1.0" encoding="ISO-8859-1"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n  "http://www.w3.org/TR/xht'
b'ml1/DTD/xhtml1-strict.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">\n<head>\n<title>Object not found!<'
b'/title>\n<link rev="made" href="mailto:webmaster@tools.ietf.org" />\n<style type="text/css"><!--/*--><![CDATA[/*><!--*/ \n    body '
b'{ color: #000000; background-color: #FFFFFF; }\n    a:link { color: #0000CC; }\n    p, address {margin-left: 3em;}\n    span {font-'
b'size: smaller;}\n/*]]>*/--></style>\n</head>\n\n<body>\n<h1>Object not found!</h1>\n<p>\n\n\n    The requested URL was not found on this '
b'server.\n\n  \n\n    If you entered the URL manually please check your\n    spelling and try again.\n\n  \n\n</p>\n<p>\nIf you think this i'
b's a server error, please contact\nthe <a href="mailto:webmaster@tools.ietf.org">webmaster</a>.\n\n</p>\n\n<h2>Error 404</h2>\n<address'
b'>\n  <a href="/">xml2rfc.tools.ietf.o